# Generated by Django 3.1.7 on 2021-03-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='intereses',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Desarrollo web'), (2, 'Analista de Datos'), (3, 'Finanzas personales')], null=True),
        ),
    ]
