# Generated by Django 2.2.9 on 2021-03-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_porttafolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Porttafolio',
        ),
    ]
