# Generated by Django 2.2.9 on 2021-03-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210315_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portafolio',
        ),
    ]
